Feature/book handlear
wisderfin/personal_library pull request #4
Opened 2024-02-26 17:30 UTC by KASSAS20

2024-02-26 18:40 UTC, kohiry reviewed
zxc pozor

2024-02-26 18:40 UTC, kohiry commented on app/components/auth.py
>      raise HTTPException(status_code=400, detail="Incorrect data")
Поменяй местами

2024-02-26 18:40 UTC, kohiry commented on app/components/book.py
> +        return f'Book: {filename}'
по хорошему json всегда возвращать

2024-02-26 18:40 UTC, kohiry commented on app/database.py
> +    async def create_user(self, user: UserSchema) -> NoReturn:
NoReturn поменяй на None

2024-02-26 18:40 UTC, kohiry commented on app/database.py
> +
Прорефактори решение с async with session. Погляди как сессия реализована в fastapi users. Слишком душно выходит с постоянно новой сесией. 
https://fastapi-users.github.io/fastapi-users/dev/configuration/oauth/

2024-02-26 18:40 UTC, kohiry commented on app/models.py
> +    id_user = Column(Integer, nullable=False)
user_id

2024-02-26 18:40 UTC, kohiry commented on app/schemes.py
> +    id_user: int
user_id

2024-02-27 11:49 UTC, KASSAS20 commented on app/components/auth.py
>      raise HTTPException(status_code=400, detail="Incorrect data")
+

2024-02-27 11:50 UTC, KASSAS20 commented on app/components/book.py
> +        return f'Book: {filename}'
+

2024-02-27 11:50 UTC, wisderfin commented on app/database.py
> +    async def create_user(self, user: UserSchema) -> NoReturn:
+

2024-02-27 11:51 UTC, KASSAS20 commented on app/models.py
> +    id_user = Column(Integer, nullable=False)
+

2024-02-27 11:52 UTC, KASSAS20 commented on app/schemes.py
> +    id_user: int
+

2024-02-27 21:12 UTC, KASSAS20 commented on app/database.py
> +
+

2024-03-01 19:00 UTC, kohiry requested changes

2024-03-01 19:00 UTC, kohiry commented on app/components/book/converter.py
> +
Нужно перенести в services. Это бизнеслогика приложения, а вся бизнеслогика находится в  services

2024-03-01 19:00 UTC, kohiry commented on app/components/book/utils.py
> +    query = text("SELECT * FROM books WHERE user_id = :user_id")
препиши на нормальный orm запрос

2024-03-01 19:00 UTC, kohiry commented on test.py
> +w(a)
убери, уже не нужен

2024-03-01 19:00 UTC, kohiry commented on app/components/auth/auth.py
>  router = router
Это нужно убрать. Создай просто здесь роутер, назови его auth_router. И уже от сюда импортируй в main.py

2024-03-01 19:00 UTC, kohiry commented on app/session.py
> +async def get_session() -> AsyncGenerator[AsyncSession, None]:
Переименуй сессию в get_async_session

2024-03-01 19:00 UTC, kohiry commented on app/components/auth/utils.py
> +async def check_login(username: str, session: AsyncSession) -> UserModel:
Булево возвращай

2024-03-01 19:00 UTC, kohiry commented on app/components/auth/utils.py
> +    return result
удали вфункцию, sswearch_user уже реализует эту логику

2024-03-01 19:00 UTC, kohiry commented on app/components/auth/utils.py
> +async def search_user(user: UserSchema, session: AsyncSession) -> UserModel:
Всё хорошо, но чтобы было лучше, сделай абстрактную модель UserOut кокой нибудь, который будет возвращаться во всех методах где ты работаешь с ORM. Это нужно для абстракции, чтобы облегчить жизнь разработчикам. тоже относится и к Book методам работы см ORM

2024-03-01 19:00 UTC, kohiry commented on app/components/book/book.py
> +router = router
кринж

2024-03-01 19:00 UTC, kohiry commented on app/components/book/book.py
> +    if file.content_type == 'application/wps-office.docx':
захардкодил файл, как будто я не могу другие загрузить. Нужно прорефакторить

2024-03-01 19:00 UTC, kohiry commented on app/components/book/book.py
> +        name = ''.join(file.filename.split('.')[:-1])
вот ответ лол :D 🧑‍🎓

2024-03-01 19:00 UTC, kohiry commented on app/components/book/book.py
> +        await connect.add_book(book=new_book, session=session)
в функцию add bok перенеси new_book. Логика работы с orm включая создание моделей, дроолжна реализовавываться в специальных методах твоегго класса работы с моделью. 
Абстрагируй бизнеслогику от конкуретных реализаций orm

2024-03-01 19:00 UTC, kohiry commented on app/components/book/book.py
> +                        session: AsyncSession = Depends(get_session)) -> dict:
Возвращай вместо dickt, pydantic класс книги. Это нужно для более понятной документации в openAPI и чтобы редактор лучше подсвечивал ошибки типов. 
Fastapi сам трансофрмирует pydantic -> dict

2024-03-01 19:00 UTC, kohiry commented on app/components/book/book.py
> +                        session: AsyncSession = Depends(get_session)) -> dict:
поэтому просто можно return BookSchema

2024-03-01 19:00 UTC, kohiry commented on app/router.py
> +router = APIRouter()
👎🏻

2024-03-01 19:00 UTC, kohiry commented on docker-compose.yaml
>    postgres:
добавь автоматический рестарт сервиса, устал перевключать

2024-03-02 07:28 UTC, KASSAS20 commented on app/components/book/converter.py
> +
+++

2024-03-02 07:42 UTC, KASSAS20 commented on app/components/auth/auth.py
>  router = router
+++

2024-03-02 07:44 UTC, KASSAS20 commented on app/session.py
> +async def get_session() -> AsyncGenerator[AsyncSession, None]:
+++

2024-03-02 07:45 UTC, KASSAS20 commented on app/components/book/book.py
> +router = router
+++

2024-03-02 07:46 UTC, KASSAS20 commented on app/components/book/book.py
> +    if file.content_type == 'application/wps-office.docx':
+++

2024-03-02 07:46 UTC, wisderfin commented on app/components/book/book.py
> +        name = ''.join(file.filename.split('.')[:-1])
+++

2024-03-02 07:47 UTC, KASSAS20 commented on app/router.py
> +router = APIRouter()
+++

2024-03-04 14:48 UTC, wisderfin commented on app/components/auth/utils.py
> +async def check_login(username: str, session: AsyncSession) -> UserModel:
+++

2024-03-06 04:49 UTC, kohiry requested changes
hell nah bruh ☠️☠️☠️☠️

2024-03-06 04:49 UTC, kohiry commented on app/components/auth/auth.py
> +    if user.password and user.login:
зачем эта проверка? Ты запрашиваешь pydantic схему. В ней нету значений none. Ещё до этой проверки приложение упадёт если у тебя нет значений по дефолту

2024-03-06 04:49 UTC, kohiry commented on app/components/auth/auth.py
> +        user_found = await connect.search_user(user, session)
Мы уже обсуждали. Чтобы бизнеслогика не была подвязана на конкретном фреймворке, делай абстрактную схему pydantic. Ты же возвращаешь UserModel из sqlalchemy.

2024-03-06 04:49 UTC, kohiry commented on app/components/auth/auth.py
> +            await connect.create_user(new_user, session)
почему это происходит не в connect_create_user? 
Модель sqlalchemy создавай в своей функции create_uiser

2024-03-06 04:49 UTC, kohiry commented on app/components/auth/auth.py
> +    user_found = await connect.check_login(username=form_data.username, session=session)
same thing. Возвращаешь UserMoedl и не pydantic абстракцию

2024-03-06 04:49 UTC, kohiry commented on app/components/book/book.py
> +        login = jwt_decode(token, 'bratislava')['login']
а это ещё что. То есть только ты можешь добавлять книги?

2024-03-06 04:49 UTC, kohiry commented on docker-compose.yaml
>    postgres:
Всё ещё жду автоматиечкий рестарт сервиса бекенда

2024-03-07 16:43 UTC, wisderfin commented on app/components/book/book.py
> +        login = jwt_decode(token, 'bratislava')['login']
с чего ты это взял?
1 строка имя книги без docx
2 строка преобразование docx в md
3 cтрока сохранение файла md
4 строка получение логина из токена с указанием секретного ключа('bratislava' уже переделал на env), для нахождения user_id и последующего добавления книги с привязкой к этому user_id

2024-03-07 17:54 UTC, wisderfin commented on app/components/book/book.py
> +                        session: AsyncSession = Depends(get_session)) -> dict:
так мне я возвращаю список книг в виде словаря, мне для него не нужна модель.

2024-03-09 06:46 UTC, kohiry approved these changes

2024-03-09 09:50 UTC, merged